/* All bilingual copy for the transformer sandbox. Technical terms
   (Q/K/V, softmax, LayerNorm…) stay English in both languages. */

export const STR = {
  en: {
    stations: [
      { id: 'emb', label: '① Sentence → vectors' },
      { id: 'attn', label: '② One head of attention' },
      { id: 'block', label: '③ The full block' },
      { id: 'gen', label: '④ Generation' },
    ],
    modelBadge: 'live model · 18 784 params · trained on a toy grammar',
    sentenceLabel: 'Sentence',
    addWord: '+ word',
    reset: '↺ reset',
    presetLabel: 'presets',

    embTitle: 'A sentence becomes a matrix',
    embCap: 'Every token gets a learned 32-number vector (an embedding). But attention treats its input as a set — it is blind to order — so a second learned vector encoding the position is added in. From here on, the sentence is just a T×32 matrix; hover any cell for its actual value.',
    embTok: 'token embeddings — what the word means',
    embPos: '+ position embeddings — where it sits',
    embSum: '= the residual stream x — what flows through the model',
    embIds: 'token ids',

    attnTitle: 'What one attention head computes',
    attnCap: 'Attention is the only place where tokens exchange information. Pick a query token and follow the pipeline: its Q vector is dotted with every token\'s K (how relevant is each?), scaled, masked, softmaxed into weights that sum to 1, and used to blend the tokens\' V vectors into the output. It is a soft lookup: Q asks, K matches, V delivers.',
    stepChips: ['Q · K', '÷ √8', 'mask', 'softmax', '× V'],
    stepCaps: [
      'The query token\'s Q is dotted with every token\'s K — one raw relevance score per token. Bigger = more relevant to this head.',
      'Scores are divided by √d_head = √8 so their variance doesn\'t blow up the softmax.',
      'The causal mask hides the future: a token may only look left. Flip it off and watch tomorrow\'s words leak in.',
      'softmax turns scores into positive weights that sum to exactly 1 — a probability of where to look.',
      'The weights blend all V vectors into one output — mostly the tokens this head decided to read.',
    ],
    maskLabel: 'causal mask',
    maskOn: 'on',
    maskOff: 'off',
    queryHint: 'click a token to make it the query ↑',
    headLabel: 'head',
    scores: 'scores  Q·K/√8',
    weightsBar: 'softmax weights (sum = 1)',
    masked: 'masked',
    qVec: 'Q of the query (8 dims)',
    kVecs: 'K of every token',
    vVecs: 'V of every token · opacity = weight',
    outVec: 'head output = Σ weight · V',
    headHints: {
      'L1H0': 'The subject-finder. Note where the query sits: on "cat" — the position that must PREDICT the verb (each position predicts the NEXT token). From there this head skips the adjacent distractor noun and grabs the true subject "dogs" with weight 0.91 (average across sentences: 0.51 vs 0.02) — that is how the model picks "sit" over "sits".',
      'L1H2': 'A second subject-finder: at verb-predicting positions it averages 0.57 on the subject vs 0.03 on a distractor noun. The model learned the same trick twice.',
      'L1H1': 'A local head: it mostly reads the previous token (avg 0.43) — cheap syntax glue.',
      'L0H0': 'Watch how much weight sits on ⟨s⟩ (avg 0.39) — a head with nothing useful to say parks its attention on the first token (an "attention sink"). Real LLMs do this too: softmax must put its 1.0 somewhere.',
      'L0H1': 'Another layer-0 head that leans on ⟨s⟩ (avg 0.39) plus the previous token — early layers mostly gather local context.',
      default: 'Move the query and watch the arcs — every head learned its own lookup pattern; nobody assigned them jobs.',
    },

    blockTitle: 'Communicate, then think',
    blockCap: 'A transformer block alternates two moves. Attention (horizontal) is where tokens exchange information — 4 heads look in 4 different ways, and their outputs are added back into each token\'s vector (the residual stream). The MLP (vertical) then processes every token separately — no token sees another inside it. Stack the block twice, normalize, and multiply by the embedding matrix to score every word in the vocabulary.',
    blockAttn: 'attention — tokens talk',
    blockAttnSub: '4 heads · each an T×T pattern (hover cells)',
    blockMlp: 'MLP — each token thinks alone',
    blockMlpSub: 'per-token: 32 → 64 → GELU → 32',
    blockResidual: '+ residual',
    blockLn: 'LayerNorm',
    blockRepeat: '× 2 layers',
    blockLogits: '→ final LN → × Eᵀ → logits over all 47 words',
    layerLabel: 'layer',
    tokenLabel: 'token',
    mlpDetail: (w) => `MLP at "${w}": 64 hidden values after GELU (dead = negative pre-activations clamped near 0)`,
    headGrid: (l, h) => `L${l}H${h}`,

    genTitle: 'Generation is a loop',
    genCap: 'The model does exactly one thing: score every word in the vocabulary as the next token. "Generation" is just feeding the choice back in and asking again — until it emits "." . These bars are the real distribution; temperature rescales the logits before softmax.',
    nextBtn: '▶ next word',
    autoBtn: '▶▶ run to "."',
    genReset: '↺ restart',
    tempLabel: 'temperature',
    greedyLabel: 'greedy',
    sampleLabel: 'sample',
    probsTitle: 'next-token distribution (top 8, real numbers)',
    cachedNote: 'greyed tokens: their K and V never change, so real systems cache them (the KV cache) instead of recomputing.',
    doneNote: 'The model emitted "." — its sentence is finished. Restart to roll another one.',
    prefixLabel: 'start from',
    lookNote: 'where the last token\'s subject-finder head (L1H0) is looking:',
  },

  zh: {
    stations: [
      { id: 'emb', label: '① 句子 → 向量' },
      { id: 'attn', label: '② 一头 attention' },
      { id: 'block', label: '③ 完整的 block' },
      { id: 'gen', label: '④ 自回归生成' },
    ],
    modelBadge: '活模型 · 18 784 参数 · 训练自玩具语法',
    sentenceLabel: '句子',
    addWord: '+ 加词',
    reset: '↺ 重置',
    presetLabel: '预置句',

    embTitle: '一句话变成一个矩阵',
    embCap: '每个 token 换成一个学出来的 32 维向量（词嵌入）。但 attention 把输入当作集合——它天生看不见顺序——所以还要加上一个编码位置的向量。从这里开始，整句话就是一个 T×32 的矩阵；悬停任意格子可以看真实数值。',
    embTok: '词嵌入——这个词是什么意思',
    embPos: '+ 位置嵌入——它站在第几个位置',
    embSum: '= 残差流 x——在模型里流动的就是它',
    embIds: 'token id',

    attnTitle: '一头 attention 到底在算什么',
    attnCap: 'attention 是 token 之间唯一交换信息的地方。选一个 query token，顺着流水线看：它的 Q 和每个 token 的 K 做点积（各自有多相关？），缩放、mask、softmax 成总和为 1 的权重，再用权重把各 token 的 V 混合成输出。本质是一次软查表：Q 提问，K 匹配，V 交货。',
    stepChips: ['Q · K', '÷ √8', 'mask', 'softmax', '× V'],
    stepCaps: [
      'query 的 Q 和每个 token 的 K 点积——每个 token 得到一个原始相关性分数，越大越相关。',
      '分数除以 √d_head = √8，防止方差过大把 softmax 推成独热。',
      '因果 mask 挡住未来：token 只能往左看。把它关掉，看看"明天的词"是怎么漏进来的。',
      'softmax 把分数变成恰好总和为 1 的正权重——一个"往哪看"的概率分布。',
      '用权重把所有 V 向量混合成一个输出——主要成分来自这头决定要读的 token。',
    ],
    maskLabel: '因果 mask',
    maskOn: '开',
    maskOff: '关',
    queryHint: '点击 token 把它设为 query ↑',
    headLabel: '头',
    scores: '分数  Q·K/√8',
    weightsBar: 'softmax 权重（和 = 1）',
    masked: '已屏蔽',
    qVec: 'query 的 Q（8 维）',
    kVecs: '每个 token 的 K',
    vVecs: '每个 token 的 V · 透明度 = 权重',
    outVec: '头输出 = Σ 权重 · V',
    headHints: {
      'L1H0': '主语侦测头。注意 query 的位置：在 "cat" 上——正是要「预测动词」的那个位置（每个位置预测的是下一个 token）。这头从这里越过紧邻的干扰名词，以 0.91 的权重直取真正的主语 "dogs"（全句平均 0.51 vs 干扰 0.02）——模型就是这样选出 "sit" 而不是 "sits" 的。',
      'L1H2': '第二个主语侦测头：在预测动词的位置上，平均给主语 0.57、给干扰名词只有 0.03。同一招模型学了两遍。',
      'L1H1': '一个局部头：主要读前一个 token（平均 0.43）——廉价的语法胶水。',
      'L0H0': '注意 ⟨s⟩ 上停了多少权重（平均 0.39）——没活干的头会把注意力泊在第一个 token 上（attention sink 现象），真实大模型也这样：softmax 的 1.0 总得有处安放。',
      'L0H1': '又一个爱靠在 ⟨s⟩ 上的第 0 层头（平均 0.39），剩下的权重读前一个词——浅层主要在收集局部上下文。',
      default: '换 query 看弧线——每个头都学出了自己的查表模式，没有人给它们分配过任务。',
    },

    blockTitle: '先交流，再独想',
    blockCap: 'transformer block 交替做两件事。attention（横向）是 token 交换信息的地方——4 个头用 4 种方式看，输出加回每个 token 的向量（残差流）。MLP（纵向）则对每个 token 单独加工——内部没有任何 token 看得见别人。这个 block 叠两层、归一化、再乘回词嵌入矩阵，就给词表里 47 个词逐一打分。',
    blockAttn: 'attention——token 之间交流',
    blockAttnSub: '4 个头 · 每个是一张 T×T 模式图（可悬停）',
    blockMlp: 'MLP——每个 token 独自思考',
    blockMlpSub: '逐 token：32 → 64 → GELU → 32',
    blockResidual: '+ 残差',
    blockLn: 'LayerNorm',
    blockRepeat: '× 2 层',
    blockLogits: '→ 末端 LN → × Eᵀ → 对全部 47 个词打分（logits）',
    layerLabel: '层',
    tokenLabel: 'token',
    mlpDetail: (w) => `"${w}" 的 MLP：GELU 后的 64 个隐藏值（负的预激活被压到 ≈0，即"死"神经元）`,
    headGrid: (l, h) => `L${l}H${h}`,

    genTitle: '生成只是一个循环',
    genCap: '模型只会做一件事：给词表里每个词打一个"下一个是它"的分。所谓"生成"，就是把选出的词喂回去再问一遍——直到它吐出 "."。这些概率条是真实分布；温度在 softmax 之前重新缩放 logits。',
    nextBtn: '▶ 下一个词',
    autoBtn: '▶▶ 跑到句号',
    genReset: '↺ 重来',
    tempLabel: '温度',
    greedyLabel: 'greedy',
    sampleLabel: '采样',
    probsTitle: '下一词分布（top 8，真实数值）',
    cachedNote: '灰显的 token：它们的 K 和 V 不会再变，真实系统会缓存（KV cache）而不是重算。',
    doneNote: '模型吐出了 "."——这句话结束了。重来可以摇出另一句。',
    prefixLabel: '起始',
    lookNote: '最后一个 token 的"主语侦测头"（L1H0）正在看谁：',
  },
};

/* preset sentences (all inside the toy vocabulary; BOS added internally) */
export const PRESETS = [
  ['the', 'cat', 'sits', 'on', 'the', 'mat', '.'],
  ['the', 'dogs', 'near', 'the', 'cat', 'sit', '.'],
  ['a', 'fox', 'jumps', 'quickly', '.'],
  ['the', 'cats', 'find', 'their', 'paws', '.'],
  ['the', 'old', 'mouse', 'sleeps', '.'],
  ['the', 'bird', 'looks', 'under', 'the', 'tree', '.'],
];
